apiVersion: v1
kind: Service
metadata:
  name: go-server
  labels:
    app: go-server
spec:
  ports:
  - port: 8866
    protocol: TCP
    targetPort: 8866
  selector:
    app: go-server
  type: ClusterIP